src/DataValues/TimeValue.php
`unserlialize` doesn't `@return` anything.
=> Remove misleading return doc

src/DataValues/TimeValue.php
I already touched quite some bits in this class, that's why I'm adding my name.
=> More specific TimeValue type hints

src/DataValues/TimeValue.php
* How to format, display and edit empty strings? Similar to https://github.com/wmde/WikibaseDataModel/pull/336 and https://github.com/wmde/WikibaseDataModel/pull/345.
* Reword exception messages.
Needs a README update and major version bump (because it's a breaking change), but I will do this later to avoid merge conflicts.
=> Disallow empty strings in TimeValue

src/ValueParsers/TimeParser.php
Either use the shortcut methods or access the protected var directly.
=> Avoid calling getOptions

src/ValueFormatters/TimeFormatter.php
=> Fix broken OPT_TIME_ISO_FORMATTER

src/ValueParsers/TimeParser.php, tests/ValueParsers/TimeParserTest.php
This is a trivial no-op change split from #27 to make it easier to review.
=> Cleanup comments in TimeParser

tests/ValueFormatters/TimeFormatterTest.php
This starts hurting. Also see #46.
=> Unblock data-values/interfaces dependency

src/ValueFormatters/TimeFormatter.php, src/ValueParsers/TimeParser.php, tests/ValueParsers/TimeParserTest.php
Another attempt to clean up all these different constructor implementations.
This is mostly split from #27.
=> Rewrite of the TimeParser constructor

src/DataValues/TimeValue.php, tests/DataValues/TimeValueTest.php
This patch does not change behavior. All it does is adding test cases and some basic refactoring:
* The day and month range checks are removed from the regex and done in PHP now.
* All year related code is in a private method now.
* I removed two duplicate test cases.
=> More TimeValue tests

src/DataValues/TimeValue.php
As suggested in https://github.com/DataValues/Time/pull/57#discussion_r28529520.
=> Fix private method name in TimeValue

tests/ValueFormatters/TimeFormatterTest.php
This is what was left from #54 after #65 was merged.
=> Refactor TimeFormatterTest

README.md, src/ValueParsers/EraParser.php, tests/ValueParsers/EraParserTest.php
* I moved the two files in commit 1 without changing anything.
* Commit 2 is my rewrite.
=> Move EraParser from Wikibase.git to DataValues Time

src/ValueFormatters/TimeFormatter.php, tests/ValueFormatters/TimeFormatterTest.php
This is split from #49 to make it easier to review. This pull requests only contains trivial refactoring that does not change any behaviour.
=> Update TimeFormatter documentation

src/ValueParsers/PhpDateTimeParser.php, tests/ValueParsers/PhpDateTimeParserTest.php
Proof that I actually worked on the flight to Wikimania 2015.
=> Add more guards to PhpDateTimeParser

src/ValueParsers/YearMonthDayTimeParser.php, tests/ValueParsers/YearMonthDayTimeParserTest.php
Proof that I actually worked on the flight to Wikimania 2015.
=> Add YearMonthDayTimeParser

src/ValueParsers/PhpDateTimeParser.php
I missed the `$year !== null` check in #77.
=> Add missing null check to PhpDateTimeParser

README.md, src/ValueParsers/YearMonthDayTimeParser.php, tests/ValueParsers/YearMonthDayTimeParserTest.php
=> YearMonthDayTimeParser can always accept month == day

README.md, src/DataValues/TimeValue.php, src/ValueParsers/IsoTimestampParser.php, tests/DataValues/TimeValueTest.php, tests/ValueParsers/IsoTimestampParserTest.php
[Bug: T110647](https://phabricator.wikimedia.org/T110647)
=> Never accept days with no month

tests/ValueParsers/PhpDateTimeParserTest.php
Plus removal of some non-helpful comments.
=> Interfaces do not have a constructor that can be disabled

README.md, Time.php
Diff:
https://github.com/DataValues/Time/compare/0.8.2...5d2ff4903bf730cf08fdfb742b5adb1ac7df3fd0
=> Prepare for a 0.8.3 release

Time.php, src/DataValues/TimeValue.php, src/DataValues/TimeValueCalculator.php, src/ValueFormatters/TimeFormatter.php, src/ValueParsers/CalendarModelParser.php, src/ValueParsers/EraParser.php, src/ValueParsers/IsoTimestampParser.php, src/ValueParsers/MonthNameUnlocalizer.php, src/ValueParsers/PhpDateTimeParser.php, src/ValueParsers/YearMonthDayTimeParser.php, tests/DataValues/TimeValueCalculatorTest.php, tests/DataValues/TimeValueTest.php, tests/ValueFormatters/TimeFormatterTest.php, tests/ValueParsers/EraParserTest.php, tests/ValueParsers/MonthNameUnlocalizerTest.php, tests/ValueParsers/PhpDateTimeParserTest.php, tests/ValueParsers/YearMonthDayTimeParserTest.php
See https://gerrit.wikimedia.org/r/281904.
=> Unify wording of "@license GPL-2.0+" lines

README.md, src/ValueParsers/EraParser.php, src/ValueParsers/IsoTimestampParser.php, src/ValueParsers/PhpDateTimeParser.php, src/ValueParsers/YearMonthTimeParser.php, src/ValueParsers/YearTimeParser.php, tests/ValueFormatters/TimeFormatterTest.php, tests/ValueParsers/CalendarModelParserTest.php, tests/ValueParsers/EraParserTest.php, tests/ValueParsers/IsoTimestampParserTest.php, tests/ValueParsers/PhpDateTimeParserTest.php, tests/ValueParsers/YearMonthDayTimeParserTest.php, tests/ValueParsers/YearMonthTimeParserTest.php, tests/ValueParsers/YearTimeParserTest.php
[Bug: T132441](https://phabricator.wikimedia.org/T132441)
=> Update and fix documentation

src/ValueParsers/MonthNameUnlocalizer.php, tests/ValueParsers/MonthNameUnlocalizerTest.php
https://gerrit.wikimedia.org/r/297756
https://phabricator.wikimedia.org/T139509
=> Do not "unlocalize" numeric months

phpcs.xml, src/ValueParsers/MonolingualMonthNameProvider.php, tests/DataValues/TimeValueCalculatorTest.php
Copied from https://github.com/DataValues/Number/pull/86.
=> Add some more PHPCS sniffs

src/DataValues/TimeValue.php
This is documentation only and does not need an immediate release.
[Bug: T168681](https://phabricator.wikimedia.org/T168681)
=> Clarify documentation of …::newFromArray

src/ValueParsers/PhpDateTimeParser.php, tests/ValueParsers/PhpDateTimeParserTest.php
[Bug: T151088](https://phabricator.wikimedia.org/T151088)
=> Block more bad "time of day" values in PhpDateTimeParser

README.md, Time.php, composer.json, src/DataValues/TimeValue.php
#122 should be part of this release, if possible.
I would also love to see #49 merged. It's more than two years old!
=> Release 0.8.5

phpcs.xml, src/ValueParsers/YearMonthTimeParser.php, tests/ValueParsers/YearMonthTimeParserTest.php
Task: https://phabricator.wikimedia.org/T233105
=> Add unicode modifier to regex

.gitignore, composer.json, tests/DataValues/TimeValueCalculatorTest.php, tests/DataValues/TimeValueTest.php, tests/ValueFormatters/TimeFormatterTest.php, tests/ValueParsers/CalendarModelParserTest.php, tests/ValueParsers/EraParserTest.php, tests/ValueParsers/IsoTimestampParserTest.php, tests/ValueParsers/MonolingualMonthNameProviderTest.php, tests/ValueParsers/MonthNameUnlocalizerTest.php, tests/ValueParsers/PhpDateTimeParserTest.php, tests/ValueParsers/ValueParserTestCase.php, tests/ValueParsers/YearMonthDayTimeParserTest.php, tests/ValueParsers/YearMonthTimeParserTest.php, tests/ValueParsers/YearTimeParserTest.php
This PR upgrades PHPUnit to 8.5 as well as removes tests dependencies between this repository and the various DataValue Repositories.
see: https://phabricator.wikimedia.org/T260915
=> Update phpunit version to 8.5

.travis.yml, composer.json, phpcs.xml, src/ValueParsers/MonthNameUnlocalizer.php, tests/ValueParsers/PhpDateTimeParserTest.php, tests/ValueParsers/YearTimeParserTest.php
Bug: [T271109](https://phabricator.wikimedia.org/T271109)
=> Add PHP 7.4 and 8 to CI

composer.json, src/ValueFormatters/TimeFormatter.php
This is needed in preparation for updating all `data-values` libs in Wikibase and in `mediawiki/vendor`
=> Update data-values/* to latest stable versions

src/ValueParsers/YearMonthTimeParser.php, tests/ValueParsers/YearMonthTimeParserTest.php
Task: https://phabricator.wikimedia.org/T233105
=> Equip YearMonthTimeParser with EraParser

README.md
=> Prepare release 1.0.4

src/DataValues/TimeValue.php
=> Implement _serialize()/__unserialize()
