wmde/Time

- src/DataValues/TimeValue.php
Note that the `TimeValue` class itself does not enforce any padding for the year. It can be 1 to 16 digits. This is intended.
This fixes #28.
Bug: [T66084](https://phabricator.wikimedia.org/T66084)
> Fix outdated TimeValue documentation

- tests/bootstrap.php
As done in several components now. The command depends on external services and can take a lot of time.
> Remove composer update from bootstrap

- src/DataValues/TimeValue.php
This documents how we are doing it **now**. Therefor I suggest to merge this, no matter what the outcome of the discussion at [T88437](https://phabricator.wikimedia.org/T88437) is. If the outcome of the discussion is different, we can change this again. But as it is now is wrong, no matter what.
Bug: [T88438](https://phabricator.wikimedia.org/T88438)
> Correct calendar model documentation

- src/DataValues/TimeValue.php
* Non-controversial rewording of the precision's documentation.
* Drop misleading line, doesn't return text.
> More specific TimeValue::$precision documentation

- src/ValueParsers/TimeParser.php
- tests/ValueParsers/TimeParserTest.php
This removes quite some obsolete code.
Originally the goal was to remove the unused newParserOptions method and to simplify the getInstance methods as much as possible. The additional changes are very closely related.
> Simplify options handling

- tests/ValueParsers/CalendarModelParserTest.php
- tests/ValueParsers/TimeParserTest.php
See https://github.com/DataValues/Common/pull/23.
This requires #43 to be merged first, therefor the failing tests.
Bug: [T92268](https://phabricator.wikimedia.org/T92268)
> Deprecate getParserClass in favor of getInstance

- src/ValueParsers/TimeParser.php
This is a trivial no-op change split from #27 to make it easier to review.
> Use self:: to address constants

- src/DataValues/TimeValue.php
- tests/DataValues/TimeValueTest.php
This implements an enforced padding to 4 digits for the year. This is the most minimal compromise. Look at how the `DateTimeParser` is implemented: It uses PHP's internal DateTime parser and needs to pad (and cut) the year to 4 digits to do this. An enforced padding to 4 digits is not crucial in this class but very convenient for almost all (external) use cases.
We can easily increase this to 16 digits later, depending on the outcome of the discussion at [T66084](https://phabricator.wikimedia.org/T66084) and related Phabricator tasks.
This also adds a test to ensure more than 16 digits for the year are not accepted.
The 1st commit is crucial, the 2nd is only a style change.
Bug: [T66084](https://phabricator.wikimedia.org/T66084)
> Enforce minimal year padding to 4 digits

- src/ValueParsers/TimeParser.php
This is a trivial no-op change split from #27 to make it easier to review. Well, almost a no-op. The exception is thrown earlier, but this doesn't change the public interface.
> Throw exception in TimeParser earlier

- tests/ValueParsers/TimeParserTest.php
This is a trivial no-op change split from #27 to make it easier to review. This is pure code reformatting, the test cases are not touched. The only changes are:
* Use `new TimeValue` instead of `TimeValue::newFromArray`.
* Use `TimeParser::CALENDAR_...` constants instead of `TimeFormatter::CALENDAR_...`.
> Simplify TimeParserTest

- src/DataValues/TimeValue.php
- tests/DataValues/TimeValueTest.php
- tests/ValueFormatters/TimeFormatterTest.php
This patch contains:
* Trim leading zeros from the year, but keep 4 digits. This is what XSD 1.0 and 1.1 say, see http://www.w3.org/TR/xmlschema11-2/#dateTime. Quote: "leading '0' digits are prohibited except to bring the digit count up to four.".
* Rename internal variables to "timestamp". That's more descriptive than "time". But don't change the public interface, that's not worth it.
Bug: [T66084](https://phabricator.wikimedia.org/T66084)
> Trim leading zeros from year in TimeValue

- composer.json
Requires https://github.com/DataValues/Interfaces/pull/9 to be released as a new version.
Bug: [T92268](https://phabricator.wikimedia.org/T92268)
Bug: [T92280](https://phabricator.wikimedia.org/T92280)
> Deprecate getFormatterClass in favor of getInstance

- README.md
- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
Two main reasons for the rename:
1. We do have two parser with the same name `TimeParser`, which is at least confusing and will turn out do be a problem if we ever try to move both into the same component. The other `TimeParser` in lib does have it's name for a good reason: It's the generic "head" parser that does nothing but call all the other, specific parsers.
2. This parser is not a generic "time" parser, it's very specific: It can only parse strings that are (or resemble) ISO timestamps.
I suggest to call this an "ISO" parser even if we are trying to avoid the word "ISO" (see [T88438](https://phabricator.wikimedia.org/T88438) and related) because this parser can parse ISO **and** stuff that resembles but is not ISO.
Bug: [T93772](https://phabricator.wikimedia.org/T93772)
> Rename TimeParser to IsoTimestampParser

- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/CalendarModelParserTest.php
- tests/ValueParsers/IsoTimestampParserTest.php
This is a major rewrite of the TimeParser class. The main change is: Most elements in the ISO time string are now optional (see the added test cases). All other changes are refactoring without changing functionality.
> Major rewrite of TimeParser

- src/ValueParsers/CalendarModelParser.php
- tests/ValueParsers/CalendarModelParserTest.php
* Trim before comparing. This is what almost all our parsers do.
* Add support for the actual URIs. If they don't identify the calendar model, I don't know. ;-)
> Add more cases to the CalendarModelParser

- src/ValueFormatters/TimeFormatter.php
- tests/ValueFormatters/TimeFormatterTest.php
This patch simply removes the discussed, confusing calendar model display from this formatter. It's split from #49 (and will cause merge conflicts, but I would like to discuss the two changes in two independent pull requests).
Note that this formatter is currently unused. The Wikibase UI uses the `HtmlTimeFormatter` instead (which, by the way, uses the calendar model as "actual" and not "preferred calendar").
This patch also removes dead code that is not used anywhere, most notably the redundant language option.
> Remove misleading calendar model output

- README.md
- src/ValueParsers/MonthNameUnlocalizer.php
- src/ValueParsers/PhpDateTimeParser.php
- tests/ValueParsers/MonthNameUnlocalizerTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
I carefully prepared the two classes to make them independent from Wikibase.git. Now it's time to move them. Almost nothing needed to change, only the namespaces, the since tags and the EraParser mock.
Bug: [T96137](https://phabricator.wikimedia.org/T96137)
> Move MonthNameUnlocalizer and PhpDateTimeParser from WB.git

- README.md
- Time.php
- src/ValueParsers/IsoTimestampParser.php
This already contains the release notes for currently not merged patches, see https://github.com/DataValues/Time/milestones/0.7.
Bug: [T96137](https://phabricator.wikimedia.org/T96137)
> Prepare 0.7.0 release

- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
See https://phabricator.wikimedia.org/T75272
> Guess Julian calendar for dates before 1582.

- src/ValueParsers/IsoTimestampParser.php
intval() is about 5 times slower than a type cast, no matter if it's done explicit (by explicitly stating (int)$string) or implicit (via $string > 0). The difference between the two is that intval() accepts a base, which is not needed in these cases.
Following the arguments given in https://forge.typo3.org/issues/54265
> Replace intval() with faster type cast

- README.md
- composer.json
- src/ValueParsers/IsoTimestampParser.php
As discussed in https://github.com/DataValues/Time/pull/66#discussion_r29860462. This is pure refactoring that doesn't change any semantics. Instead of first re-concatenating sign and year, both are checked independently. The strlen check is not necessary. Even if an INT32 "overflow" happens, it will not cause any trouble because PHP doesn't overflow like C.
> Simplify calendar model detection code

- README.md
- src/DataValues/TimeValue.php
- src/ValueFormatters/TimeFormatter.php
- src/ValueParsers/CalendarModelParser.php
- src/ValueParsers/IsoTimestampParser.php
- tests/ValueFormatters/TimeFormatterTest.php
- tests/ValueParsers/CalendarModelParserTest.php
The IsoTimestampParser class moved to this component recently (which raises the question if the deprecation is needed or if we can remove the constants right away). The TimeFormatter was living here for a longer time. Now that both are in the same component it does not make much sense to keep both constants. The migration was suggested several times in other pull requests.
You may ask if this is Wikidata-specific knowledge. I disagree. It's just a string, nothing more. Also note that it was living in this component for a long time before.
> Move calendar model constants to TimeValue

- src/DataValues/TimeValue.php
- tests/DataValues/TimeValueTest.php
[Bug: T97511](https://phabricator.wikimedia.org/T97511)
Side note: I did a bit of benchmarking on that class' constructor because I added quite some code recently. I was afraid I introduced a bottleneck but couldn't find one. The regex can not be avoided. Squishing the range checks into the regex (as it was before) does make construction ~5% faster but is not worth it in my opinion because it dramatically decreases readability. The majority of construction time is spend on the many `is_...` checks. None can be avoided.
> Fix allowed leap seconds range

- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
This patch fixes several issues and adds a new feature:
* Colons in time are optional, e.g. T1530 or T153001 are valid times according to ISO.
* Reduce year padding to 4 digits for consistency with TimeValue.
* 3 leap seconds (60, 61 and 62) can not exist; for consistency with TimeValue (see #64).
[Bug: T97511](https://phabricator.wikimedia.org/T97511)
> Optional colons in ISO time

- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
All these paddings do not have an effect because `TimeValue` normalizes the timestamp anyway. But the code is easier to read and maintain if the year padding is the same everywhere.
> Harmonize year padding in IsoTimestampParser

- README.md
- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
See README. This fixes an actual bug, but because we block hour, minute and second precisions this is currently not relevant for Wikibase.git.
> Fix IsoTimestampParser on midnight

- README.md
- src/DataValues/TimeValue.php
- src/ValueParsers/IsoTimestampParser.php
- tests/DataValues/TimeValueCalculatorTest.php
- tests/DataValues/TimeValueTest.php
- tests/ValueFormatters/TimeFormatterTest.php
- tests/ValueParsers/IsoTimestampParserTest.php
Also see:
* https://github.com/wmde/DataValuesJavascript/pull/68
* https://gerrit.wikimedia.org/r/#/c/194306/
[Bug: T99911](https://phabricator.wikimedia.org/T99911)
> Unify names of time precision constants

- tests/ValueParsers/CalendarModelParserTest.php
This makes this test more independent from a class it should not depend on. I already did the same in a lot of other tests in Wikibase.git.
> Make CalendarModelParserTest more independent

- README.md
- Time.php
- src/DataValues/TimeValue.php
This partly "reverts" #42 by re-adding backwards compatible aliases.
[Bug: T99911](https://phabricator.wikimedia.org/T99911)
> Add old precision constants as aliases

- src/ValueParsers/YearMonthDayTimeParser.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
This fixes an actual bug: Month and day must be padded to 2 digits before passing to TimeValue.
And adds a feature: Negative numbers can not be confused with anything else, so we can also accept negative years in the [-31..0] range.
> Improve YearMonthDayTimeParser

- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
Two actual changes:
* I'm decreasing the limit for the year from 60 to 32. Before, the idea was to be sure the number can not be confused with anything, not even with a minute or second. But: How can a datetime string start with minute or second? It can start with the day, so the limit must be 32.
* If the string starts with a sign character, the first number must be the year (which other part of a datetime string will ever be signed?) and all years are allowed.
> Allow a few more edge cases in IsoTimestampParser

- src/ValueParsers/YearMonthDayTimeParser.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
I suggest to merge #80 first because they conflict.
> Do not parse a HH:MM:SS time as a date

- README.md
- Time.php
- src/ValueParsers/YearMonthDayTimeParser.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
You could say that this is a breaking change, because some inputs are now parsed different. E.g. "2015.12.11" was parsed before but is rejected now because the parser can not know if it's YMD or YDM.
I would argue that this is purely a bugfix. E.g. "2015.31.12" was rejected before but is accepted now. "2015.12.11" should have never been parsed. The contract of the class did not changed: Some inputs are accepted and some not. This did not changed. Code using this component should get this update silently.
> YearMonthDayTimeParser must be aware of rare YDM format

- README.md
- src/ValueParsers/YearMonthDayTimeParser.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
This was already merged in #87, but not into master but into the #86 branch. I expected both to appear in master when merged in the right order, but according to the graph the merge commit in #87 did not became part of #86. Let's try again.
> YearMonthDayTimeParser can always accept month == day

- tests/ValueParsers/YearMonthDayTimeParserTest.php
This had tests for the day being zero, but no test for the month being zero.
> Add "month is zero" tests for YearMonthDayTimeParser

- tests/DataValues/TimeValueCalculatorTest.php
This is usually not helpful, and we usually do not do this. I added such comments for a short time, but I think this was a mistake.
> Drop dataProvider parameter documentation

- src/ValueParsers/IsoTimestampParser.php
- src/ValueParsers/YearMonthDayTimeParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
This patch fixes multiple bugs:
* YearMonthDayTimeParser did not accepted any option. Not it forwards to IsoTimestampParser and uses it's calendar model and precision detection.
* When you set the precision option in the API, it's a string, not an integer. This was not accepted.
* When you used an invalid precision, this was sometimes silently ignored, but should throw an exception.
[Bug: T128783](https://phabricator.wikimedia.org/T128783)
> Fix IsoTimestamp/YearMonthDayTimeParser not accepting precisions

- src/ValueParsers/IsoTimestampParser.php
- src/ValueParsers/PhpDateTimeParser.php
- src/ValueParsers/YearMonthDayTimeParser.php
As far as I can tell this is **not** a breaking change. These constants are not used anywhere except for exception messages. There was quite some confusion about these constants when we introduced new parsers and renamed existing parser classes. With this patch I'm applying the most simple naming scheme: identical to the relevant part of the class name, lowercase, separated with dashes.
Please merge https://github.com/DataValues/Geo/pull/56 and https://gerrit.wikimedia.org/r/257592 along with this.
> Fix format name strings in parsers

- src/ValueParsers/MonolingualMonthNameProvider.php
- src/ValueParsers/MonthNameProvider.php
- tests/ValueParsers/MonolingualMonthNameProviderTest.php
Moved from the repo directory from Wikibase.git. The interface will be used in multiple parsers. The static implementation is mostly for tests, but I did not wanted to have this as a private detail in the tests folder because I want to use this in repo tests too.
> Add MonthNameProvider and MonolingualMonthNameProvider

- README.md
- Time.php
- src/ValueParsers/YearMonthTimeParser.php
- src/ValueParsers/YearTimeParser.php
- tests/ValueParsers/YearMonthTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
The two "new" parsers are moved over here from Wikibase.git, which became possible after #105. I avoided changing any detail in the code of these classes. This is a pure move, only namespaces, imports and PHPDoc tags are changed. I know that these classes need more love (note the todo) and I will continue working on them.
[Bug: T132441](https://phabricator.wikimedia.org/T132441)
> Release 0.8.4 with Year(Month)TimeParsers

- src/ValueParsers/YearMonthTimeParser.php
- src/ValueParsers/YearTimeParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
All this does is avoiding duplicate code.
[Bug: T132441](https://phabricator.wikimedia.org/T132441)
> Avoid duplicate CalendarModelParser initialization code

- src/ValueParsers/YearMonthTimeParser.php
- tests/ValueParsers/YearMonthTimeParserTest.php
This class was added in #111, but not touched in this pull request on purpose. It had several oversights and bugs I want to fix before a release. Most notably: "January -150" becomes January 150 _after_ Christ.
[Bug: T132441](https://phabricator.wikimedia.org/T132441)
> Fix and expand incomplete YearMonthTimeParser

- src/ValueParsers/YearTimeParser.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
- tests/ValueParsers/YearMonthTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
[Bug: T133299](https://phabricator.wikimedia.org/T133299)
> Test for newline injection vector in time parsers

- src/ValueParsers/YearTimeParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
The YearTimeParser test was introduced in #116 and described the current behavior of the parser. In this patch I'm changing this behavior and add trimming, as all other parsers already do.
I'm using existing tests to not make the test case collection to big and time consuming.
For the same reason I'm removing redundant test cases from IsoTimestampParserTest.
> Trim in YearTimeParser and add more whitespace tests

- src/DataValues/TimeValue.php
- src/ValueParsers/IsoTimestampParser.php
- tests/DataValues/TimeValueTest.php
- tests/ValueParsers/IsoTimestampParserTest.php
Same as #88, but for combinations that include non-zero hours, minutes or seconds.
This is not relevant in production because our validators don't accept anything but `…T00:00:00Z`. Still a bug that needs fixing.
I'm also untangling a few of the `if`s because of the [guard design pattern](https://en.wikipedia.org/wiki/Guard_(computer_science)). It is of no benefit to use `else` because all these `if`s throw an exception anyway.
> Never accept hour, minute or second with no day

- phpcs.xml
- src/ValueParsers/IsoTimestampParser.php
- src/ValueParsers/YearMonthTimeParser.php
- tests/ValueParsers/YearMonthTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
… and enable the OperatorSpacing rule. It turned out to be helpful in other code repositories. This code here is already fine.
> Enable space before single line comment PHPCS rule

- .travis.yml
- README.md
- composer.json
- phpcs.xml
I also need to pin the PHPUnit and MediaWiki CodeSniffer versions, otherwise incompatible versions will be used.
[Bug: T165300](https://phabricator.wikimedia.org/T165300)
> Raised required PHP version from 5.3 to 5.5

- composer.json
- phpcs.xml
Similar to all "Remove non-standard Composer commands" patches I'm removing the awkward "phpcs" command here. I'm also simplifying the command a lot, which makes it even more obvious that this is not needed as a separate command. Before it made some sense to have a shortcut. Now it doesn't any more.
I just forgot to simplify this command in #130.
> Remove not needed "composer phpcs" command

- src/ValueParsers/IsoTimestampParser.php
This is already checked by the base class. The $value passed to stringParse is guaranteed to be a string (hence the name of the method).
Please merge https://github.com/DataValues/Number/pull/114 along with this, as it is the same patch in an other component.
> Remove duplicate is_string check from IsoTimestampParser

- composer.json
- tests/ValueFormatters/TimeFormatterTest.php
- tests/ValueParsers/CalendarModelParserTest.php
- tests/ValueParsers/EraParserTest.php
- tests/ValueParsers/IsoTimestampParserTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
- tests/ValueParsers/YearMonthTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
This is not a breaking change and can be merged any time. But it can also wait. It must not be merged immediately. Keeping this a little longer doesn't hurt. I'm just uploading this patch so we don't forget.
> Drop compatibility with DataValues Interfaces <0.2 and Common <0.3

- src/ValueParsers/IsoTimestampParser.php
- tests/ValueParsers/IsoTimestampParserTest.php
- tests/ValueParsers/YearMonthDayTimeParserTest.php
I do classify this as a bug. An unknown calendar string should either be kept as it is (TimeValue happily stores any non-empty string, and the validators we have in place will reject everything that's not a Wikidata concept URI). Or it should be rejected if the relevant CalendarModelParser does not understand it (which is what this patch does). But unknown strings should never silently become the Gregorian URI.
You might think this is a breaking change because code that could never fail before now throws a ParseException. But note this was always possible and documented, see IsoTimestampParser::stringParse. The exception is just thrown for one more reason now.
[Bug: T141518](https://phabricator.wikimedia.org/T141518)
> Parse and refuse invalid calendar option

- .travis.yml
- composer.json
All of the removed versions (other than HHVM, I suppose) are EOLed already, so I don’t think we need to consider this a breaking change.
7.3 is added, but 7.4 isn’t added yet, because it currently fails in Travis CI because some of our used packages are so old. I’ll fix that separately.
> Refresh PHP versions

- src/ValueParsers/IsoTimestampParser.php
Will silence some deprecations.
> IsoTimestampParser: Only call ctype_digit with strings

- src/ValueParsers/PhpDateTimeParser.php
- tests/ValueParsers/PhpDateTimeParserTest.php
Starting from PHP 8.1.7 `DateTime` interprets `YYYY-DDD` as the DDDth day of the year.
We need to take this into account (to not accidentally mangle input into that format).
See also:
- https://bugs.php.net/bug.php?id=51987
- https://www.php.net/ChangeLog-8.php#8.1.7
> Update PhpDateTimeParser for PHP 8.1.7+

- .travis.yml
- composer.json
- src/ValueParsers/MonthNameUnlocalizer.php
- src/ValueParsers/YearMonthTimeParser.php
- tests/DataValues/TimeValueCalculatorTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
On top of some minor changes, this splits a new `splitByYearMonth` from `YearMonthTimeParser::stringParse` (in order to make `mediawiki/mediawiki-codesniffer` `^39` happy).
> Add PHP 8.1 to CI, update mediawiki/mediawiki-codesniffer to ^39

- README.md
- composer.json
There’s no reason to require *exactly* version 3.0.0, we want people to use 3.1.0.
> Relax data-values/data-values version constraint

- composer.json
- src/DataValues/TimeValue.php
- src/DataValues/TimeValueCalculator.php
- src/ValueFormatters/TimeFormatter.php
- src/ValueParsers/CalendarModelParser.php
- src/ValueParsers/IsoTimestampParser.php
- src/ValueParsers/PhpDateTimeParser.php
- src/ValueParsers/YearMonthDayTimeParser.php
- src/ValueParsers/YearMonthTimeParser.php
- src/ValueParsers/YearTimeParser.php
- tests/DataValues/TimeValueCalculatorTest.php
- tests/ValueFormatters/TimeFormatterTest.php
- tests/ValueParsers/PhpDateTimeParserTest.php
- tests/ValueParsers/ValueParserTestCase.php
- tests/ValueParsers/YearMonthTimeParserTest.php
- tests/ValueParsers/YearTimeParserTest.php
This repository is currently using version 34 of the Mediawiki coding style phpcs rules. It should be upgraded to the latest version.
Besides being simply different, the newer versions of the rules introduce, for example,
MediaWiki.Usage.NullableType.ExplicitNullableTypes, which enforces compliance with coming deprecation rules in PHP 8.4 concerning nullable types. If the code does not remove the soon-to-be-deprecated form of nullable type declarations, the library will no longer be usable in Mediawiki for PHP 8.4 deployments.
Bug: T379481
> Upgrade mediawiki-codesniffer to latest version (45.0.0)
